<a href="https://colab.research.google.com/github/Egeoltaa/Yapayzeka/blob/main/Python-numpayipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


#1) (10,15,30,45,60) değerlerine sahip numpy dizisi oluştur

In [2]:
result=np.array([10,15,30,45,60])
result

array([10, 15, 30, 45, 60])

# 2) 5-15 arasındaki sayılarla bir diz oluştur.

In [3]:
result=np.arange(5,15)
result

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#3 ) 50-100 arasında 5 er 5 er bir dizi oluştur

In [4]:
result=np.arange(50,100,5)
result

array([50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

#4) 10 elemanlı sıfırlardan oluşan bir dizi oluştur

---



In [5]:
result=np.zeros(10)
result

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#5) 10 elemanlı birlerden oluşan bir dizi oluştur

In [6]:
result=np.ones(10)
result

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#6) 0 ile 100 arasında eşit aralıklı 5 sayı üretin

In [7]:
result=np.linspace(0,100,5)
result

array([  0.,  25.,  50.,  75., 100.])

#7) 10 ile 30 arasında rastgele 5 tam sayı oluştur

In [8]:
result=np.random.randint(10,30,5)
result

array([22, 13, 13, 16, 26])

#8) -1 ile 1 arsında 10 adet sayı üret

In [22]:
result=np.random.randn(10)
result

array([-1.03413443e+00, -6.65100378e-04, -7.55547991e-02,  1.43681481e+00,
       -6.41611938e-01,  2.43192355e-01, -2.24733523e-01, -2.35261475e-01,
       -1.84336346e+00, -3.51725234e-01])

#9) 3x5 boyutlarında 10 ile 50 arasında rastgele bir matris oluştur

In [10]:
result=np.random.randint(10,50,15).reshape(3,5)
result

array([[19, 24, 32, 12, 46],
       [21, 12, 26, 31, 31],
       [13, 27, 34, 12, 41]])

#10) Üretilen matrisin satır ve sütün sayılarının toplamlarını hesapla

In [32]:
matris=np.random.randint(10,50,15).reshape(3,5)
satir=np.sum(matris,axis=1)
sutun=np.sum(matris,axis=0)
result

array([[17, 29, 13, 45, 16],
       [47, 27, 42, 10, 42],
       [46, 37, 22, 15, 24]])

#11) Üretilen matrisin en büyük ve en küçük ve ortalaması nedir?

In [31]:
result=np.random.randint(10,50,15).reshape(3,5)
enBuyuk=np.max(result)
enKucuk=np.min(result)
ortalama=np.mean(result)
result

array([[17, 29, 13, 45, 16],
       [47, 27, 42, 10, 42],
       [46, 37, 22, 15, 24]])

#12) Üretilen matrisin en büyük değerinin indeksi kaçtır =

In [30]:
result=matris.argmax()
result=matris.argmin()
result

2

#13) 10 ile 20 arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz

In [28]:
result=np.arange(10,20)[0:3]
result

array([10, 11, 12])

#14) Üretilen dizinin elemanlarını tersten yazdır

In [33]:
result=np.arange(10,20)[::-1]
result

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

#15) Üretilen matrisin ilk satırnını seçiniz

In [35]:
result=matris[0]
result

array([39, 27, 36, 12, 45])

#16) Üretilien matrisin  2.satır 3.sütündaki elemanı hangisidir

In [36]:
result=matris[1,2]

#17) Üretilen matrisin tüm satırlardaki ilk elemanı çiziniz

In [37]:
result=matris[:,0]
result

array([39, 15, 23])

#18) Üretilen matrisin  her bir elemanının karesini alınız

In [38]:
result=np.square(matris)
result

array([[1521,  729, 1296,  144, 2025],
       [ 225, 1764, 1521,  256,  361],
       [ 529,  324,  100,  196,  729]])

#19) Üretilen matris elemanlarının hangisi pozitif çift sayıdır?

In [39]:
result=matris[matris%2==0]
result

array([36, 12, 42, 16, 18, 10, 14])